package Objects

enum class PersonData (
        val index: Int,
        val email: String,
        val passwordPekama: String,
        val passwordEmail: String,
        val passwordBox: String,
        val passwordXero: String,
        val passwordLinkedIn: String,
        val firstName: String,
        val secondName: String,
        val initials: String,
        val company: String,
        val businessType: String,
        val role: String,
        val phone: String,
        val fax: String,
        val mobile: String,
        val legalEntity: String,
        val street: String,
        val zip: String,
        val city: String,
        val region: String,
        val country: String,
        val teamName: String,
        val teamFullName: String,
        val teamCode: String,
        val teamInitials: String,
        val teamEmail: String,
        val teamStreet: String,
        val teamZip: String,
        val teamCity: String,
        val teamRegion: String,
        val teamCountry: String
        )
{
   
    USER00(
            1,
            "email",
            "passwordPekama",
            "passwordEmail",
            "passwordBox",
            "passwordXero",
            "passwordLinkedIn",
            "firstName",
            "lastName",
            "initials",
            "company",
            "businessType",
            "role",
            "phone",
            "fax",
            "mobile",
            "legalEntity",
            "street",
            "zip",
            "city",
            "region",
            "country",
            "teamName",
            "teamFullName",
            "teamCode",
            "teamInitials",
            "teamEmail",
            "teamStreet",
            "teamZip",
            "teamCity",
            "teamRegion",
            "teamCountry"
    )   
}
